#nenad_test_homepage:
 #   path:     /homepage
  #  defaults: { _controller: NenadTestBundle:Default:index }

nenad_test_email:
    path:     /homepage/email
    defaults: { _controller: NenadTestBundle:Default:email }

nenad_email_post:
    path: /homepage/email/post
    defaults: { _controller: NenadTestBundle:Default:emailpost}

nenad_homepage:
  path: /
  defaults: { _controller: NenadTestBundle:Default:index }
#
login:
    pattern:   /login
    defaults:  { _controller: NenadTestBundle:Secured:login }
#login_check:
#    pattern:   /login_check
