
emaillogin:
    path: /email/login
    defaults: { _controller: NenadTestBundle:Secured:login}
    requirements:
            _method:  GET|POST

homepagelogin:
    pattern:   /homepage/login
    defaults:  { _controller: NenadTestBundle:Secured:login }

login_check:
    pattern:   /login_check

test_security:
    pattern:   /secure_area
    defaults:  {_controller: NenadTestBundle:Secured:hello }

logout:
    path:      /logout

nenad_send:
    path:      /email/sent
    defaults:  { _controller: NenadTestBundle:Secured:contact }
