#nenad_test_homepage:
 #   path:     /homepage
  #  defaults: { _controller: NenadTestBundle:Default:index }

#nenad_test_email:
 #   path:     /homepage/email
  #  defaults: { _controller: NenadTestBundle:Default:email }

login:
    pattern:   /login
    defaults:  { _controller: NenadTestBundle:Secured:login }
login_check:
    pattern:   /login_check
