_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

login:
    pattern:   /login
    defaults:  { _controller: NenadTestBundle:Secured:login }
login_check:
    pattern:   /login_check

test_security:
    pattern: /secured_area
    defaults: {_controller: SimpleProfileBundle:Secured:hello }
logout:
    path:     /logout
