security:
    encoders:
        Nenad\TestBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    providers:
        main:
            entity:
                class: Nenad\TestBundle\Entity\User
                property: username

    firewalls:
        secured_area:

            pattern:    ^/
            anonymous: ~
            form_login:
                default_target_path: /secure_area
                login_path:  homepagelogin
                check_path:  login_check
            logout:
                path:   /logout
                target: /homepage/login


    access_control:
         - { path: ^/secure_area, roles: ROLE_USER }
